CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE parse_failures (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    url character varying(500) NOT NULL,
    fetched_at timestamp with time zone NOT NULL,
    reason text NOT NULL,
    shape_hash character varying(64),
    CONSTRAINT pk_parse_failures PRIMARY KEY (id)
);

CREATE TABLE sets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    slug character varying(200) NOT NULL,
    name character varying(200) NOT NULL,
    discovered_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_sets PRIMARY KEY (id)
);

CREATE TABLE shapes (
    hash character varying(64) NOT NULL,
    shape_json jsonb NOT NULL,
    sample_url character varying(500) NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_shapes PRIMARY KEY (hash)
);

CREATE TABLE visits (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    kind smallint NOT NULL,
    url character varying(500) NOT NULL,
    card_id bigint,
    fetched_at timestamp with time zone NOT NULL,
    http_status integer NOT NULL,
    outcome smallint NOT NULL,
    shape_hash character varying(64),
    CONSTRAINT pk_visits PRIMARY KEY (id)
);

CREATE TABLE cards (
    id bigint NOT NULL,
    set_id bigint NOT NULL,
    url character varying(500) NOT NULL,
    name character varying(300) NOT NULL,
    image_hash character varying(64),
    image_fetched_at timestamp with time zone,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    last_visited_at timestamp with time zone,
    observed_sales_per_day double precision,
    any_bucket_at_cap boolean NOT NULL,
    CONSTRAINT pk_cards PRIMARY KEY (id),
    CONSTRAINT fk_cards_sets_set_id FOREIGN KEY (set_id) REFERENCES sets (id) ON DELETE RESTRICT
);

CREATE TABLE populations (
    card_id bigint NOT NULL,
    grader character varying(8) NOT NULL,
    grade smallint NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    population integer NOT NULL,
    CONSTRAINT pk_populations PRIMARY KEY (card_id, grader, grade, observed_at),
    CONSTRAINT fk_populations_cards_card_id FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE RESTRICT
);

CREATE TABLE price_months (
    card_id bigint NOT NULL,
    tier integer NOT NULL,
    month date NOT NULL,
    observed_at timestamp with time zone NOT NULL,
    price_cents integer NOT NULL,
    CONSTRAINT pk_price_months PRIMARY KEY (card_id, tier, month, observed_at),
    CONSTRAINT fk_price_months_cards_card_id FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE RESTRICT
);

CREATE TABLE sales (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    card_id bigint NOT NULL,
    source character varying(16) NOT NULL,
    source_id character varying(200) NOT NULL,
    sold_on date NOT NULL,
    grade_tier character varying(40) NOT NULL,
    price_cents integer NOT NULL,
    listed_price_cents integer,
    title character varying(500) NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_sales PRIMARY KEY (id),
    CONSTRAINT fk_sales_cards_card_id FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE RESTRICT
);

CREATE INDEX ix_cards_last_visited_at ON cards (last_visited_at);

CREATE INDEX ix_cards_set_id ON cards (set_id);

CREATE INDEX ix_parse_failures_fetched_at ON parse_failures (fetched_at);

CREATE INDEX ix_sales_card_id_sold_on ON sales (card_id, sold_on);

CREATE UNIQUE INDEX ix_sales_source_source_id ON sales (source, source_id);

CREATE UNIQUE INDEX ix_sets_slug ON sets (slug);

CREATE INDEX ix_visits_fetched_at ON visits (fetched_at);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260728032826_InitialCreate', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE sets ADD last_walked_at timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260728185424_AddSetLastWalkedAt', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE cards ADD failure_streak integer NOT NULL DEFAULT 0;

ALTER TABLE cards ADD quarantined_until timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260728195602_AddCardQuarantine', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE cards ALTER COLUMN image_hash TYPE character varying(128);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260801024826_WidenImageHash', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE cards ADD delisted_at timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260803133815_AddCardDelisted', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE cards ADD delisted_probed_at timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260807025014_AddDelistedProbedAt', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE shapes RENAME TO fingerprints;

ALTER TABLE fingerprints RENAME CONSTRAINT pk_shapes TO pk_fingerprints;

ALTER TABLE fingerprints RENAME COLUMN shape_json TO names;

ALTER TABLE visits RENAME COLUMN shape_hash TO fingerprint_hash;

ALTER TABLE parse_failures RENAME COLUMN shape_hash TO fingerprint_hash;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260808022824_RenameShapesToFingerprints', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE cards ADD not_a_card_at timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260808194030_AddCardNotACard', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE cards ADD refresh_requested_at timestamp with time zone;

CREATE INDEX ix_cards_refresh_requested_at ON cards (refresh_requested_at) WHERE refresh_requested_at IS NOT NULL;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260809153250_AddCardRefreshRequestedAt', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE cards ADD near_miss_at timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260812162439_AddCardNearMissAt', '10.0.10');

COMMIT;

START TRANSACTION;
CREATE TABLE tcgdex_enrichments (
    card_id bigint NOT NULL,
    computed_at timestamp with time zone NOT NULL,
    status smallint NOT NULL,
    card_number character varying(32),
    set_official_size integer,
    tcgdex_set_id character varying(32),
    tcgdex_card_id character varying(64),
    tcgdex_name character varying(300),
    tcgdex_version character varying(64) NOT NULL,
    CONSTRAINT pk_tcgdex_enrichments PRIMARY KEY (card_id, computed_at),
    CONSTRAINT fk_tcgdex_enrichments_cards_card_id FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE RESTRICT
);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260813055713_AddTcgdexEnrichments', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE cards ADD gone_at timestamp with time zone;

CREATE INDEX ix_cards_gone_at ON cards (gone_at) WHERE gone_at IS NOT NULL;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260813234040_AddCardGoneAt', '10.0.10');

COMMIT;

START TRANSACTION;
CREATE TABLE card_tagging (
    card_id bigint NOT NULL,
    status smallint NOT NULL,
    method smallint NOT NULL,
    tagged_name character varying(300) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_card_tagging PRIMARY KEY (card_id),
    CONSTRAINT fk_card_tagging_cards_card_id FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE RESTRICT
);

CREATE TABLE set_details (
    set_id bigint NOT NULL,
    match_status smallint NOT NULL,
    code character varying(32),
    released_on date,
    series character varying(100),
    era character varying(24),
    CONSTRAINT pk_set_details PRIMARY KEY (set_id),
    CONSTRAINT fk_set_details_sets_set_id FOREIGN KEY (set_id) REFERENCES sets (id) ON DELETE RESTRICT
);

CREATE TABLE species (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(200) NOT NULL,
    generation smallint NOT NULL,
    region character varying(24) NOT NULL,
    color character varying(24) NOT NULL,
    habitat character varying(24),
    status smallint NOT NULL,
    stage smallint NOT NULL,
    evolves_from_species_id integer,
    gradient_start character varying(7) NOT NULL,
    gradient_end character varying(7) NOT NULL,
    CONSTRAINT pk_species PRIMARY KEY (id),
    CONSTRAINT fk_species_species_evolves_from_species_id FOREIGN KEY (evolves_from_species_id) REFERENCES species (id) ON DELETE RESTRICT
);

CREATE TABLE card_species (
    card_id bigint NOT NULL,
    species_id integer NOT NULL,
    method smallint NOT NULL,
    CONSTRAINT pk_card_species PRIMARY KEY (card_id, species_id),
    CONSTRAINT fk_card_species_cards_card_id FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE RESTRICT,
    CONSTRAINT fk_card_species_species_species_id FOREIGN KEY (species_id) REFERENCES species (id) ON DELETE RESTRICT
);

CREATE TABLE species_egg_groups (
    species_id integer NOT NULL,
    egg_group character varying(24) NOT NULL,
    CONSTRAINT pk_species_egg_groups PRIMARY KEY (species_id, egg_group),
    CONSTRAINT fk_species_egg_groups_species_species_id FOREIGN KEY (species_id) REFERENCES species (id) ON DELETE RESTRICT
);

CREATE TABLE species_names (
    species_id integer NOT NULL,
    language character varying(12) NOT NULL,
    name character varying(200) NOT NULL,
    CONSTRAINT pk_species_names PRIMARY KEY (species_id, language),
    CONSTRAINT fk_species_names_species_species_id FOREIGN KEY (species_id) REFERENCES species (id) ON DELETE RESTRICT
);

CREATE TABLE species_types (
    species_id integer NOT NULL,
    slot smallint NOT NULL,
    type character varying(16) NOT NULL,
    CONSTRAINT pk_species_types PRIMARY KEY (species_id, slot),
    CONSTRAINT fk_species_types_species_species_id FOREIGN KEY (species_id) REFERENCES species (id) ON DELETE RESTRICT
);

CREATE INDEX ix_card_species_species_id_card_id ON card_species (species_id, card_id);

CREATE INDEX ix_species_evolves_from_species_id ON species (evolves_from_species_id);

CREATE UNIQUE INDEX ix_species_slug ON species (slug);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260815032212_AddPokedex', '10.0.10');

COMMIT;

