// <auto-generated />
using System;
using CardStock.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardStock.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CardStockDbContext))]
    [Migration("20260811203346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cardstock")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardStock.Infrastructure.Persistence.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "cardstock");
                });

            modelBuilder.Entity("CardStock.Infrastructure.Persistence.Entities.UserSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_sessions_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", "cardstock");
                });

            modelBuilder.Entity("CardStock.Infrastructure.Persistence.ScraperReadModels.ScraperCard", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DelistedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delisted_at");

                    b.Property<string>("ImageHash")
                        .HasColumnType("text")
                        .HasColumnName("image_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NotACardAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_a_card_at");

                    b.Property<long>("SetId")
                        .HasColumnType("bigint")
                        .HasColumnName("set_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_scraper_cards");

                    b.ToTable((string)null);

                    b.ToView("cards", "public");
                });

            modelBuilder.Entity("CardStock.Infrastructure.Persistence.ScraperReadModels.ScraperPopulation", b =>
                {
                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<string>("Grader")
                        .HasColumnType("text")
                        .HasColumnName("grader");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint")
                        .HasColumnName("grade");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.HasKey("CardId", "Grader", "Grade", "ObservedAt")
                        .HasName("pk_scraper_populations");

                    b.ToTable((string)null);

                    b.ToView("populations", "public");
                });

            modelBuilder.Entity("CardStock.Infrastructure.Persistence.ScraperReadModels.ScraperPriceMonth", b =>
                {
                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents");

                    b.HasKey("CardId", "Tier", "Month", "ObservedAt")
                        .HasName("pk_scraper_price_months");

                    b.ToTable((string)null);

                    b.ToView("price_months", "public");
                });

            modelBuilder.Entity("CardStock.Infrastructure.Persistence.ScraperReadModels.ScraperSale", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<string>("GradeTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grade_tier");

                    b.Property<int?>("ListedPriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("listed_price_cents");

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents");

                    b.Property<DateOnly>("SoldOn")
                        .HasColumnType("date")
                        .HasColumnName("sold_on");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_scraper_sales");

                    b.ToTable((string)null);

                    b.ToView("sales", "public");
                });

            modelBuilder.Entity("CardStock.Infrastructure.Persistence.ScraperReadModels.ScraperSet", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_scraper_sets");

                    b.ToTable((string)null);

                    b.ToView("sets", "public");
                });

            modelBuilder.Entity("CardStock.Infrastructure.Persistence.Entities.UserSession", b =>
                {
                    b.HasOne("CardStock.Infrastructure.Persistence.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_users_user_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
